# Generated by Django 5.1.4 on 2025-08-05 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_challenge_description'),
        ('leaderboard', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='challenges', through='leaderboard.LeaderboardEntry', to=settings.AUTH_USER_MODEL),
        ),
    ]
