# Generated by Django 5.1.4 on 2025-08-05 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_initial'),
        ('challenges', '0002_alter_challenge_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoaction',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eco_actions', to='challenges.challenge'),
        ),
        migrations.AlterField(
            model_name='ecoaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eco_actions', to=settings.AUTH_USER_MODEL),
        ),
    ]
