# Generated by Django 5.1.4 on 2025-08-10 16:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_ecoaction_challenge_alter_ecoaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoaction',
            name='performed_on',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
