# Generated by Django 5.1.4 on 2025-08-10 16:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0004_ecoaction_performed_on"),
        ("challenges", "0003_challenge_participants"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("transport", "Public Transport"),
                            ("plastic", "Avoided Plastic"),
                            ("vegetarian", "Vegetarian Meal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("points", models.IntegerField(default=0)),
                (
                    "challenge",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_templates",
                        to="challenges.challenge",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
