# Generated by Django 5.1.4 on 2025-08-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_actiontemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiontemplate',
            name='action_type',
            field=models.CharField(choices=[('transport', 'Public Transport'), ('plastic', 'Avoided Plastic'), ('vegetarian', 'Vegetarian Meal'), ('energy', 'Energy Saving'), ('water', 'Water Saving')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ecoaction',
            name='action_type',
            field=models.CharField(choices=[('transport', 'Public Transport'), ('plastic', 'Avoided Plastic'), ('vegetarian', 'Vegetarian Meal'), ('energy', 'Energy Saving'), ('water', 'Water Saving')], max_length=20),
        ),
    ]
