# Generated by Django 5.1.4 on 2025-08-05 15:37

import server.apps.users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_city'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', server.apps.users.models.CustomUserManager()),
            ],
        ),
    ]
